---
:concurrency: 2
staging:
  :concurrency: 5
production:
  :concurrency: 5
:queues:
  - default
  - receiver_queue

:schedule:
  volunteer_feedback_scheduler:
    cron: '0 18 * * * Europe/Prague'
    class: VolunteerFeedbackScheduler